#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'Paver==1.0.5','console_scripts','paver'
__requires__ = ['Paver==1.0.5', 'TurboGears >= 1.0, < 2']
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('Paver==1.0.5', 'console_scripts', 'paver')()
    )
